name: Deploy Danksalad Frontend to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: ssh to ec2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.REMOTE_IP }}
        port: ${{ secrets.REMOTE_SSH_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_PRIVATE_KEY }}
        script: |
          cd dan-financial-book
          git pull
          npm run build
          sudo systemctl restart nginx.service
